### ISSUE TITLE
opening inbox with aos> #Inbox doesnt work

### ISSUE THREAD

**Issue by Papilllion** [permaweb/ao-cookbook#101]
![image](https://github.com/permaweb/ao-cookbook/assets/49870334/c6c3935f-cc18-4d39-b45b-4efa2c0f6143)

process suggested in docs doesnt work

**Comment by andytudhope** [comment]
This is because you copied the `aos>` from the page too. Just write `#Inbox` and it should give you what you need.

This is proof of why #103 is a good idea @twilson63 and should likely be a standard across the docs

**Comment by TillaTheHun0** [comment]
Thanks @andytudhope

#103 makes examples in Cookbook clearer. Closing this.
