### ISSUE TITLE
Make an alt version of ao-cookbook

### ISSUE THREAD

**Issue by HelloRWA** [permaweb/ao-cookbook#119]
I just read through the ao cookbook.
It's exciting for the new tech!

I am just thinking about making a Chinese translation for the cookbook, at the same time, I make an alt version for the ao-cookbook, if you like, I can transfer the repo to permaweb org.

[Source](https://github.com/HelloRWA/ao-cookbook-nuxt3)
[Preview](https://ao-cookbook.web3blog.world/)

![Screenshot 2024-03-02 at 12 40 00](https://github.com/permaweb/ao-cookbook/assets/141105328/8b324437-0f4d-4c97-9265-0df200238162)

![Screenshot 2024-03-02 at 12 39 23](https://github.com/permaweb/ao-cookbook/assets/141105328/f2e7587e-1576-4146-b769-c3adb7c66baf)

## Difference from ao-cookbook

* Move top-level item to the top nav
  * reduce the length of left aside menu
  * Only show sub-level menu items in the current top-level menu
* For multiple languages, making a different branch to host this with different sub-domains will be better.
* Support doc search internal
* Use [Nuxt3 Docs Template](https://docs-template.nuxt.dev/)
* Require to buy a [Nuxt3 UI Pro license](https://ui.nuxt.com/pro?aff=KokMD) to deploy, it's ok to dev in localhost without the licence key

**Comment by twilson63** [comment]
Sounds great, DYK, vitepress has i8n built in?

https://vitepress.dev/guide/i18n

Y not use the builtin and keep things consistent, with the permaweb cookbook we found it easier for collaborators to keep up with changes

IMO, the only thing worse than no documentation is documentation that is out of date. Forking and maintaining a separate version may lead to out of date docs.

**Comment by HelloRWA** [comment]
> Sounds great, DYK, vitepress has i8n built in?
> 
> https://vitepress.dev/guide/i18n
> 
> Y not use the builtin and keep things consistent, with the permaweb cookbook we found it easier for collaborators to keep up with changes
> 
> IMO, the only thing worse than no documentation is documentation that is out of date. Forking and maintaining a separate version may lead to out of date docs.

ya, I see.

I know vitepress has i18n ;)
Just feel nuxt3 solution works better.
Actually, for the content part, the doc content is almost the same as they both use markdown (https://content.nuxt.com/).
So just copying the markdown file to sync docs is alright.
