### ISSUE TITLE
Error trying to boot aos. 

### ISSUE THREAD

**Issue by crooks-s** [permaweb/ao-cookbook#123]
**Description**
Trying to boot aos but receiving ```An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.```

**Desktop:**
 - macOS
 - Version: 14.2.1
- BuildVersion: 23C71

**Details**
- Node v20.11.1
1. Ran ```npm i -g https://get_ao.g8way.io/```
2. Ran ```aos```
3. Received ```An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.```
4. Ran ```DEBUG=1```. See screenshot below for output.
5. Ran ```HTTPS_PROXY=http://localhost:3000 aos``` → same output as step 3.

**Screenshots**
<img width="1283" alt="Screenshot 2024-03-03 at 1 09 33 PM" src="https://github.com/permaweb/ao-cookbook/assets/115957278/3577fd0c-e3f9-47b4-9362-14ef1c7d767f">
<br />
<img width="1124" alt="Screenshot 2024-03-03 at 1 39 53 PM" src="https://github.com/permaweb/ao-cookbook/assets/115957278/c8272f80-9d7f-49ad-ab5d-ad201bc4a900">

<br />
<img width="1011" alt="Screenshot 2024-03-03 at 1 12 02 PM" src="https://github.com/permaweb/ao-cookbook/assets/115957278/b3e5deb7-442b-44f7-bc74-12815a3c52a1">

**Comment by crooks-s** [comment]
Not sure what happened exactly, but I was able to boot aos shortly after opening this Issue. Closed my terminal and attempted to boot aos again, receiving same error as before.

**Comment by HelloRWA** [comment]
I tried different locations's VPS server still did not work, I find out solution in Discord:
Try with a different process name to fix this.

```sh
aos name1
aos name2
aos name3
...
```

Just switch to more name, till it works.

**Comment by twilson63** [comment]
OkLet’s set up a time to debug via screen share DM me on discord @rakis-tomSent from my iPhoneOn Mar 4, 2024, at 5:55 AM, HelloRWA ***@***.***> wrote:﻿
I tried different locations's VPS server still did not work, I find out solution in Discord:
Try with a different process name to fix this.
aos name1
aos name2
aos name3
...
Just switch to more name, till it works.

**Comment by xiaoliwe** [comment]
same issue for macOS(iTerm2). So, what's the next step? 
thanks.

**Comment by HelloRWA** [comment]
> same issue for macOS(iTerm2). So, what's the next step? thanks.

try `aos [your-process-name1]`
if it does not work, change to another name, such as `your-process-name2`
try many times till it works.

I fix it this way.

**Comment by TillaTheHun0** [comment]
This looks to have been a result of gateway congestion and overall network congestion, which has workarounds as described above. Closing for now, but if issue happens again feel free to ask in Discord or file another issue.
