### ISSUE TITLE
Cannot receive Morpheus's response. 

### ISSUE THREAD

**Issue by xiaoliwe** [permaweb/ao-cookbook#130]
According to this: https://cookbook_ao.g8way.io/tutorials/begin/messaging.html [Section: Message]. 
Cannot receive Morpheus's response after executing the send command. 
<img width="454" alt="Screenshot 2024-03-05 at 17 04 09" src="https://github.com/permaweb/ao-cookbook/assets/9930176/4bf0cd63-f7a3-4cb8-a4cf-caec08e240a7">

Does mistake something? Or Morpheus isn't working fine? 

Thanks.

**Comment by HelloRWA** [comment]
> Hey, as you can see message has been added to the outbox. Morpheus will respond soon. Since, alot of msgs are in the queue it might be taking a little time.

I think it can not get response event you wait for more minutes..
Seems the cookbook update a new Morpheus process id already.

**Comment by TillaTheHun0** [comment]
Thanks. Yep, we swapped in [a new Morpheus](https://cookbook_ao.arweave.dev/tutorials/begin/messaging.html#step-4-store-morpheus-s-process-id). Please try that one.
