### ISSUE TITLE
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.

### ISSUE THREAD

**Issue by nice2mu** [permaweb/ao-cookbook#134]
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.

**Comment by TillaTheHun0** [comment]
This could be do to your network, or a proxy. Could you try again and also try naming your `aos`? ie:

```sh
aos test1
```

That will spin up a new process.

**Comment by TillaTheHun0** [comment]
This looks to have been a result of gateway congestion and overall network congestion, which has workarounds as described above. Closing for now, but if issue happens again feel free to ask in Discord or file another issue.

**Comment by sweet-smail** [comment]
@TillaTheHun0 

I encountered the same problem
device:
M1 pro

node -v
v20.15.1
