### ISSUE TITLE
toggle between themes not working as expected

### ISSUE THREAD

**Issue by Not-Sarthak** [permaweb/ao-cookbook#142]
The theme doesn't seem to toggle from dark to light mode as seen in the video below.

[Screencast from 08-03-24 10:57:32 PM IST.webm](https://github.com/permaweb/ao-cookbook/assets/92942966/7a64fb4a-cb69-4fd5-9645-d520beacdc15)

**Comment by TillaTheHun0** [comment]
@Not-Sarthak thanks for reporting. This is an issue with ArDrive Turbo that we use to upload the cookbook assets -- seen this before. I'll reach out to them to fix.
