### ISSUE TITLE
Error occurred trying to boot AOS. Please check your access points.

### ISSUE THREAD

**Issue by huangyuzhang** [permaweb/ao-cookbook#207]
Having `aos` installed globally, the following error occured when executing `aos` command (MacOS 13.6.6 Intel chip):

<img width="682" alt="截屏2024-06-04 10 23 58" src="https://github.com/permaweb/ao-cookbook/assets/40261916/ed869cbb-65a3-4e4c-b7eb-ece16c77c251">

Please Help!

**Comment by twilson63** [comment]
Please check out our FAQ on Discord - RE: VPN

https://discord.com/channels/1210396395643863101/1215587206635323393/1215988920353816717

If this does not fix your issues, please chat in the #support channel.

Here is a temporary invite to the discord server: https://discord.gg/F4hwjU2d

**Comment by hapeeeeee** [comment]
> 请查看我们在 Discord 上的常见问题解答 - 回复：VPN
> 
> https://discord.com/channels/1210396395643863101/1215587206635323393/1215988920353816717
> 
> 如果这不能解决您的问题，请在 #support 频道中聊天。
> 
> 这是对 discord 服务器的临时邀请： https://discord.gg/F4hwjU2d

I encountered the same issue. Clicking the link in the response shows that the invitation has expired and there's nothing there. What should I do?

**Comment by TillaTheHun0** [comment]
Here's an updated [link to Discord](https://discord.gg/qWgGxJKwNJ)

Closing this here.
