### ISSUE TITLE
Questions around AO 

### ISSUE THREAD

**Issue by johnnynanjiang** [permaweb/ao-cookbook#211]
1. Are there any examples (either code repos or live demos) that can help people understand how OA works in the form of Web apps or other apps.

2. My understanding is that one can use programming languages such as LUA, Rust, C++ on OA. Is JavaScript supported so that one can utilise 3rd party JavaScript libraries on OA.

Thanks and regards,

**Comment by TillaTheHun0** [comment]
1. There are lots of folks building applications on ao. Two that come to mind are [Bazar](https://github.com/permaweb/bazar) and [LlamaLand](https://github.com/elliotsayes/Reality).

2. It depends on which layer you're building at. When building a web application that uses ao, you can use any tech you'd like, including the [`aoconnect`](https://github.com/permaweb/ao/tree/main/connect) for interacting with the processes on the ao network.

You join other builders in [our Discord](https://discord.gg/qWgGxJKwNJ) to see what everyone is building! That would be the place to ask specific questions.

Going to close this here, thanks for the questions.
