### ISSUE TITLE
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.

### ISSUE THREAD

**Issue by sweet-smail** [permaweb/ao-cookbook#212]
node version 

v20.15.1

device

m1 pro 
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/1d00a4e9-508d-457a-8072-ab1275286d02">

**Comment by ETH-KT** [comment]
I also encountered the same problem as you

**Comment by ETH-KT** [comment]
the terminal proxy is turned on

**Comment by TillaTheHun0** [comment]
Please use the [ao Discord](https://discord.gg/qWgGxJKwNJ) to troubleshoot these sorts of issues.

Typically these are network or gateway related. Closing this out here.
