### ISSUE TITLE
feat(spawn): Mention the `Authority` Tag 

### ISSUE THREAD

**Issue by twilson63** [permaweb/ao-cookbook#214]
In the Spawn Reference Section, mention the Authority Tag 

| Authority | Identifiers that the process is able to accept transactions from that are not the owner or the process | 0-n | "fcoN_xJeisVsPXA-trzVAuIiqO3ydLQxM-L4XbrQKzY" |

**Comment by xgocn** [comment]
fcoN_xJeisVsPXA-trzVAuIiqO3ydLQxM-L4XbrQKzY is MU's id?
