### ISSUE TITLE
How could I realize `aos [myProcess] --cron 5-minutes` in sub-process‘ lua code when using ao.spawn 

### ISSUE THREAD

**Issue by xgocn** [permaweb/ao-cookbook#225]
```
    local newProcess = ao.spawn(ao.env.Module.Id, {
      Authority = ao.id
    }).receive()

    ao.send({
      Target = newProcess.Process,
      Action = 'Eval',
      Data = [[
            Handlers.add(
                'CronTick', 
                Handlers.utils.hasMatchingTag('Action', 'Cron'), 
                 function(msg)
                    msg.reply({ Data = 'Pong'})
                end
            )
        ]]
    })
```

How could I realize `aos [myProcess] --cron 5-minutes` in sub-process‘ lua code when using ao.spawn

**Comment by twilson63** [comment]
```lua
Spawn(ao.env.Module.Id, {
  Authority = ao.id,
  ["Cron-Tag-Action"] = "Cron",
  ["Cron-Interval"] = "5-minutes"
 })
```

You will have to use the MU REST endpoint to engage monitoring...

`POST https://mu.ao-testnet.xyz/monitor/:processid`

**Comment by xgocn** [comment]
When we define spawn, newprocess has not defined handler yet. Is cron already running? When we add handlers.add in the later part, it has business logic. Before that, is cron executing an empty loop?

**Comment by twilson63** [comment]
Yes cron calculates implicit messages based on interval, if you don't
handle them, they will go into your inbox

**Comment by xgocn** [comment]
I just ran ```curl -X POST  https://mu.ao-testnet.xyz/monitor/b3WAvKqYrdsLBtGkNVPD5RpeJERy1WiCA3LBbf6LmPI
{"error":"this.binary.subarray is not a function"}```
got ```{"error":"this.binary.subarray is not a function"}```

**Comment by xgocn** [comment]
I believe the newprocess is running，because I send a `Ping` and got a `Pong`

**Comment by xgocn** [comment]
this my code
```
local newProcess = ao.spawn(ao.env.Module.Id, {
        Authority = ao.id,
        ["Cron-Tag-Action"] = "Cron",
        ["Cron-Interval"] = "10-seconds"
    }).receive()

    print(newProcess.Process)

    DB:exec(string.format("UPDATE npc SET proc_id = '%s' WHERE id = %d", newProcess.Process,npcId))

    ao.send({
      Target = newProcess.Process,
      Action = 'Eval',
      Data = [[
            Handlers.add(
                'ping',
                Handlers.utils.hasMatchingTag('Action', 'Ping'),
                function(msg)
                    msg.reply({ Data = 'Pong'})
                end
            )
            
            -- 每 30 秒更新孢子和抗体
            Handlers.add(
                'CronTick', 
                Handlers.utils.hasMatchingTag('Action', 'Cron'), 
                function(msg)
                    print("NPC CHECKING.")
                    msg.reply({ Data = "NPC has died." })
                end
            )
        ]]
    })
```

**Comment by xgocn** [comment]
who is the singer of a cron handler,maybe no one?

**Comment by twilson63** [comment]
singer?

If you mean signer, cron messages are generated implicitly.

Thx

Tom

**Comment by xgocn** [comment]
yes, signer,if cron messages are generated implicitly,the 
```
Handlers.add(
                'CronTick', 
                Handlers.utils.hasMatchingTag('Action', 'Cron'), 
                function(msg)
                    **ao.send({Target ='l7ph6gka-mmrVE5P23lRa-1BWgQC8MXH8FcTbs6wk_U',Action = 'Ping'})**
                    msg.reply({ Data = "NPC has died." })
                end
            )
```

the ao.send didn‘t work in my test

**Comment by twilson63** [comment]
do you have a test script you can share?

**Comment by xgocn** [comment]
[test.zip](https://github.com/user-attachments/files/16982685/test.zip)

**Comment by xgocn** [comment]
And I‘m not the only one who met the problem

**Comment by twilson63** [comment]
Sorry, traveling, I will review your code as soon as possible.

Thanks

Tom

**Comment by xgocn** [comment]
Have a good time!

**Comment by antaintan** [comment]
I had the same problem

**Comment by windTrace** [comment]
yes, bug exists when call ao.send in Cron of spawned sub-process

**Comment by xgocn** [comment]
To be continued here https://github.com/permaweb/ao-cookbook/issues/228
