### ISSUE TITLE
docs: Signer for process spawning generates error if Arweave wallet is not installed

### ISSUE THREAD

**Issue by skyf0xx** [permaweb/ao-cookbook#232]
The signer specified [here](https://cookbook_ao.g8way.io/guides/aoconnect/spawning-processes.html#spawning-a-process-in-nodejs) needs Arweave wallet installed

```typescript
import { createDataItemSigner, spawn } from "@permaweb/ao-sdk";

const processId = await spawn({
  // The Arweave TXID of the ao Module
  module: "module TXID",
  // The Arweave wallet address of a Scheduler Unit
  scheduler: "_GQ33BkPtZrqxA84vM8Zk-N2aO0toNNu_C-l-rawrBA",
  // A signer function containing your wallet
  signer: createDataItemSigner(globalThis.arweaveWallet),
  /*
    Refer to a Processes' source code or documentation
    for tags that may effect its computation.
  */
  tags: [
    { name: "Your-Tag-Name-Here", value: "your-tag-value" },
    { name: "Another-Tag", value: "another-value" },
  ],
});
```

However, some browser applications might not need Arweave wallet specifically. E.g.
1. They might authenticate the user in some other way
2. They might be trivial tasks that do not need the extra UX burden of installing / signing a wallet

In this case, a custom signer can be used as bellow:
```typescript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
//@ts-nocheck

import * as WarpArBundles from 'warp-arbundles';
const pkg = WarpArBundles.default ? WarpArBundles.default : WarpArBundles;
const { createData, ArweaveSigner } = pkg;

export function createDataItemSigner(wallet) {
  const signer = async ({ data, tags, target, anchor }) => {
    const signer = new ArweaveSigner(wallet);
    const dataItem = createData(data, signer, { tags, target, anchor });
    return dataItem.sign(signer).then(async () => ({
      id: await dataItem.id,
      raw: await dataItem.getRaw(),
    }));
  };

  return signer;
}
```

**Comment by twilson63** [comment]
All messages for AO need to be signed. There are many different ways to sign dataItems, but they MUST be signed by a wallet.

**Comment by skyf0xx** [comment]
> MUST be signed by a wallet.

Yes - the suggested code is a generalization of the original code.

I should have been more specific:


In the original code, arweave wallet is being used to sign it but it errors if the developer tries a different wallet.

```typescript
import { createDataItemSigner, spawn } from "@permaweb/ao-sdk";
...
  signer: createDataItemSigner(globalThis.arweaveWallet),
```

In the generalized form, createDataItemSigner accepts other wallets
```typescript
  const signer = new ArweaveSigner(wallet);
```

The suggestion is to update the docs so it also has the generalized form as well, where the developer can have granular control of the UX

ref [discord conversation](https://discord.com/channels/1210396395643863101/1210606000030359562/1288782043932655720):

**Comment by twilson63** [comment]
Added more detail about signers:

@skyf0xx 

https://cookbook_ao.g8way.io/guides/aoconnect/sending-messages.html

https://cookbook_ao.g8way.io/guides/aoconnect/signers.html

Does this satisfy your issue?

**Comment by skyf0xx** [comment]
Thank you this clarifies it 🙏
