### ISSUE TITLE
docs: Allow versioning for discoverability and feedback

### ISSUE THREAD

**Issue by skyf0xx** [permaweb/ao-cookbook#233]
Since the protocol is still evolving, new versions are currently posted on [hackmd](https://hackmd.io/@ao-docs/rk_R2S_O0#AOS-Release-200-AOS-200)

However, [enabling versioning](https://vvp.imb11.dev/guide/adding-version) on the cookbook would allow for easier management but also easier retrieval and feedback loops from devs

**Comment by PatrickMockridge** [comment]
I second this, as a noob it would make follow along and keeping up much easier.

**Comment by twilson63** [comment]
AO is still in testnet, that said, we will start to publish release notes on the cookbook. And incorporate latest features into the guides.
