### ISSUE TITLE
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.

### ISSUE THREAD

**Issue by doxulovezh** [permaweb/ao-cookbook#99]
![image](https://github.com/permaweb/ao-cookbook/assets/54633419/c735a8d4-93df-41cf-948c-12d169284165)

**Comment by dgu0323** [comment]
i encounter a  same error,     macbook m1 max  
node --version
v21.2.0

**Comment by dgu0323** [comment]
It works fine on Amazon ec2  Linux,  but mac is not work  , should i  compile it from source ？

**Comment by TillaTheHun0** [comment]
Hey @dgu0323 do you get the same error when using node `20`?

**Comment by timwhite2** [comment]
same error,macbook pro m1 pro
node -v:v20.11.1

**Comment by guotie** [comment]
same problem, sad

**Comment by twilson63** [comment]
Try to set the `DEBUG=1 aos`

Then post the output to this issue, this will help us debug further

**Comment by guotie** [comment]
seems network problem

```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///opt/homebrew/lib/node_modules/@permaweb/aos/node_modules/zod/lib/index.mjs:3173:32 {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.
```

**Comment by twilson63** [comment]
@TillaTheHun0 Take a look at this error seems to be related to streams...

**Comment by dbcfd** [comment]
Slightly different error for me

`Error: Error while communicating with MU: {"cause":{"code":"ECONNRESET","host":"mu.ao-testnet.xyz","port":443,"localAddress":null}}
    at file:///Users/dbrowning/.nvm/versions/node/v20.8.0/lib/node_modules/@permaweb/aos/node_modules/@permaweb/aoconnect/dist/index.js:100:27
    at file:///Users/dbrowning/.nvm/versions/node/v20.8.0/lib/node_modules/@permaweb/aos/node_modules/@permaweb/aoconnect/dist/index.js:24:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.`

Interestingly, the server is pingable and nmap against 443 shows open.

**Comment by twilson63** [comment]
npm i -g https://get_ao.g8way.io

Version 1.10.8

Run (replace XXXX with the port your proxy is on)

```
HTTPS_PROXY=localhost:XXXX aos
```

**Comment by crypto-yus** [comment]
Welcome to the ao Operating System.
{ error: 'GRAPHQL Error trying to locate process.' }
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.
same problem
